apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-application
  namespace: default
spec:
  destination:
    namespace: default # Nginx를 배포할 대상 네임스페이스
    server: miles-test # Kubernetes API 서버 주소
  project: default # ArgoCD 프로젝트 이름
  source:
    repoURL: https://github.com/mileslee-nsuslab/sample-argocd # 애플리케이션 소스 코드가 저장된 Git 리포지토리 URL
    path: / # 리포지토리 내의 애플리케이션 경로
    targetRevision: HEAD # 배포할 리비전 (브랜치, 태그 또는 커밋 해시)
  syncPolicy:
    automated:
      prune: true # 더 이상 사용되지 않는 리소스 삭제
      selfHeal: true # 실패한 배포를 자동으로 복구
