apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3 # 배포할 파드의 개수
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest # 사용할 Nginx 도커 이미지
        ports:
        - containerPort: 80 # Nginx가 수신 대기할 포트
        volumeMounts:
        - name: sample-secret
          mountPath: /temp/secret
          subPath: secret
      volumes:
      - name: sample-secret
        secret: 
          secretName: sample-secret

