apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    targetRevision: 2.12.0
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    helm:
      releaseName: sealed-secrets
      parameters:
      - name: "fullnameOverride"
        value: sealed-secrets-controller
  destination:
    name: miles-test
    namespace: kube-system

